[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
addopts = "--strict-markers -vv --nbmake --nbmake-timeout=6000"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
testpaths = [
    "tests",
    "notebooks"
]
